# LAB-03: Encryption Incompatibility — Responder (Libreswan)
# Configured ONLY with AES-128-CBC (No overlap with AES-256-GCM)
config setup
    logfile=/var/log/pluto.log

conn incompat-enc
    left=192.168.100.20
    leftid=@gateway-b.stateflux.lab
    leftsubnet=10.2.0.0/16
    right=192.168.100.10
    rightid=@gateway-a.stateflux.lab
    rightsubnet=10.1.0.0/16
    authby=secret
    ikev2=insist
    ike=aes128-sha2_256;modp2048
    esp=aes128-sha2_256
    auto=add
