"""
STATEFLUX — Controlled Lab API Routes
=====================================
Phase 4 — Migration Planner + Real IPsec Lab + Prediction Validation

Provides endpoints for running controlled strongSwan & Libreswan scenarios,
retrieving test run outcomes, and inspecting prediction validation metrics.
Commands are strictly isolated to predefined test scenarios.
"""

from typing import Optional
from fastapi import APIRouter, HTTPException, status
from pydantic import Field

from app.models.base import StatefluxBaseModel
from app.models.lab import LabResult, LabValidationMetrics
from app.services.lab_service import LabService

router = APIRouter(prefix="/lab", tags=["Controlled Lab"])

_lab_service = LabService()


def get_lab_service() -> LabService:
    return _lab_service


class LabRunRequest(StatefluxBaseModel):
    """Payload to trigger a controlled lab scenario run."""
    scenario_id: str = Field(
        "LAB-01",
        description="Predefined scenario ID: LAB-01 (Secure), LAB-02 (Weak), LAB-03 (Enc Incompatible), LAB-04 (DH Incompatible), LAB-05 (Latent Rekey).",
    )
    inject_mismatch: bool = Field(False, description="Simulate a prediction mismatch for model verification testing.")


@router.post(
    "/run",
    response_model=LabResult,
    status_code=status.HTTP_201_CREATED,
    summary="Execute Controlled Lab Scenario",
    description="Run a controlled strongSwan / Libreswan test scenario to validate simulation predictions.",
)
async def run_lab_scenario(request: LabRunRequest) -> LabResult:
    try:
        result = _lab_service.run_scenario(
            scenario_id=request.scenario_id,
            inject_mismatch=request.inject_mismatch,
        )
        return result
    except ValueError as val_err:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(val_err),
        )
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Lab run failed: {str(exc)}",
        )


@router.get(
    "/validation",
    response_model=LabValidationMetrics,
    summary="Get Prediction Validation Metrics",
    description="Retrieve aggregate prediction agreement metrics between STATEFLUX simulation predictions and real lab outcomes.",
)
async def get_validation_metrics() -> LabValidationMetrics:
    return _lab_service.get_validation_metrics()


@router.get(
    "/{run_id}",
    response_model=LabResult,
    summary="Get Lab Run Result",
    description="Retrieve details, logs, and prediction match status for a specific lab run.",
)
async def get_lab_run(run_id: str) -> LabResult:
    run = _lab_service.get_run(run_id)
    if not run:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Lab run '{run_id}' not found.",
        )
    return run


@router.get(
    "/{run_id}/evidence",
    response_model=list[dict],
    summary="Get Lab Run Evidence",
    description="Retrieve all evidence items (logs, results) generated by a specific controlled lab run.",
)
async def get_lab_run_evidence(run_id: str) -> list[dict]:
    run = _lab_service.get_run(run_id)
    if not run:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Lab run '{run_id}' not found.",
        )
    from app.api.routes.evidence_route import get_evidence_engine
    ev_engine = get_evidence_engine()
    all_evidence = ev_engine.get_all_evidence()
    run_evidence = [e.model_dump() for e in all_evidence if run_id in e.source_id or run.scenario_id.lower() in e.source_id.lower()]
    return run_evidence

