"""
STATEFLUX — Future Schema: ChangeRequest
==========================================
PHASE STATUS: PLACEHOLDER — Phase 8/9 Implementation

A ChangeRequest represents a proposed modification to a Policy.
It is a DELTA, not an absolute policy definition.

The Change-Impact Simulator applies a ChangeRequest delta to a
base Policy to produce a new Policy, then evaluates every tunnel
in the fleet under the new policy.

Sources:
  - MANUAL: typed directly by the analyst via the Policy Center UI
  - AI_PARSED: generated by the AI Assistant from a natural language input
  - IMPORTED: loaded from an external file or integration

The AI parser MUST NOT be the authoritative source for the
resulting policy state. The deterministic Policy Engine validates
and applies the delta.
"""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict


class ChangeRequest(BaseModel):
    """A structured delta to apply to an existing Policy (Phase 8/9 placeholder)."""

    model_config = ConfigDict(extra="forbid")

    change_request_id:     str
    label:                 str
    description:           Optional[str]  = None

    # Source metadata
    source:                str            = "MANUAL"   # MANUAL | AI_PARSED | IMPORTED
    raw_input:             Optional[str]  = None       # Original NL text if AI_PARSED

    # The policy this delta applies to
    base_policy_id:        str

    # Delta operations (to be fully designed in Phase 8)
    add_forbidden_encryption:   list[str] = []
    remove_forbidden_encryption: list[str] = []
    set_required_encryption:    list[str] = []
    set_pfs_required:           Optional[bool] = None
    set_minimum_dh_group:       Optional[int]  = None
    set_replay_protection:      Optional[bool] = None
    set_ike_version_minimum:    Optional[int]  = None

    # Resulting policy after application (set by Phase 8 engine)
    resulting_policy_id: Optional[str]      = None

    # Validation state
    validated:           bool               = False
    validation_errors:   list[str]          = []

    created_by:          Optional[str]      = None
    created_at:          Optional[datetime] = None
