"""
STATEFLUX — AI Reasoning & Explanation Model
============================================
Phase 5 — AI + Evidence Engine + PCAP Analysis + Security Reporting

Defines structured AI explanations grounded strictly in deterministic evidence.
AI explains, translates, and summarizes facts without inventing cryptographic data
or altering deterministic severity.
"""

from typing import Optional, Any
from datetime import datetime, timezone
from pydantic import Field

from app.models.base import StatefluxBaseModel
from app.models.negotiation_space import ConfidenceLevel


class AIExplanation(StatefluxBaseModel):
    """A strictly grounded explanation generated by the AI Reasoning Layer."""
    explanation_id: str
    target_id: str                             # finding_id, tunnel_id, or simulation_id
    target_type: str = "FINDING"               # "FINDING" | "TUNNEL" | "FLEET" | "CHANGE_IMPACT" | "MIGRATION" | "LAB"
    summary: str                               # High-level executive synthesis
    why_it_matters: str                        # Operational or security context
    evidence: list[str] = Field(default_factory=list) # Traceable evidence IDs
    observed_facts: list[str] = Field(default_factory=list)
    derived_facts: list[str] = Field(default_factory=list)
    unknowns: list[str] = Field(default_factory=list)
    recommended_action: str
    confidence: ConfidenceLevel = ConfidenceLevel.HIGH
    provider: str = "STATEFLUX_GROUNDED_AI"
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    guardrails_enforced: bool = True
    metadata: dict[str, Any] = Field(default_factory=dict)
