# LAB-04: DH Mismatch — Responder (strongSwan)
# Configured ONLY with DH Group 14 (modp2048) — No overlap with Group 20!
connections {
    incompat-dh {
        local_addrs = 192.168.100.20
        remote_addrs = 192.168.100.10
        version = 2
        proposals = aes256gcm16-prfsha256-modp2048

        local {
            auth = psk
            id = gateway-b.stateflux.lab
        }
        remote {
            auth = psk
            id = gateway-a.stateflux.lab
        }

        children {
            incompat-dh {
                local_ts = 10.2.0.0/16
                remote_ts = 10.1.0.0/16
                esp_proposals = aes256gcm16-modp2048
            }
        }
    }
}

secrets {
    ike-lab04 {
        secret = "StatefluxControlledLabSecretKey2026!"
    }
}
