# LAB-04: DH Mismatch — Initiator (strongSwan)
# Configured ONLY with DH Group 20 (ecp384)
connections {
    incompat-dh {
        local_addrs = 192.168.100.10
        remote_addrs = 192.168.100.20
        version = 2
        proposals = aes256gcm16-prfsha256-ecp384

        local {
            auth = psk
            id = gateway-a.stateflux.lab
        }
        remote {
            auth = psk
            id = gateway-b.stateflux.lab
        }

        children {
            incompat-dh {
                local_ts = 10.1.0.0/16
                remote_ts = 10.2.0.0/16
                esp_proposals = aes256gcm16-ecp384
                start_action = start
            }
        }
    }
}

secrets {
    ike-lab04 {
        secret = "StatefluxControlledLabSecretKey2026!"
    }
}
