# LAB-05: Latent Rekey Failure — Responder (Libreswan)
# Initially allows AES-128-CBC for initial SA.
# Post-change policy is reloaded: ONLY AES-256-GCM is allowed.
# When initiator attempts to rekey with AES-128-CBC, rekey negotiation FAILS.
config setup
    logfile=/var/log/pluto.log

conn latent-test
    left=192.168.100.20
    leftid=@gateway-b.stateflux.lab
    leftsubnet=10.2.0.0/16
    right=192.168.100.10
    rightid=@gateway-a.stateflux.lab
    rightsubnet=10.1.0.0/16
    authby=secret
    ikev2=insist
    # Policy update removes aes128:
    ike=aes_gcm256-sha2_256-ecp_384
    esp=aes_gcm256-ecp_384
    auto=add
    salifetime=30s
