# STATEFLUX Controlled Lab — Libreswan base configuration
config setup
    logfile=/var/log/pluto.log
    logtime=yes
    logappend=no
    dumpdir=/var/run/pluto

conn net-net
    left=192.168.100.20
    leftid=@gateway-b.stateflux.lab
    leftsubnet=10.2.0.0/16
    right=192.168.100.10
    rightid=@gateway-a.stateflux.lab
    rightsubnet=10.1.0.0/16
    authby=secret
    ikev2=insist
    ike=aes_gcm256-sha2_256-ecp_384,aes128-sha2_256;modp2048
    esp=aes_gcm256-ecp_384,aes128-sha2_256
    auto=add
    salifetime=3600s
