# LAB-02: Weak but Functional Fallback (AES-128-CBC / DH Group 14 / No PFS)
connections {
    weak-tunnel {
        local_addrs = 192.168.100.10
        remote_addrs = 192.168.100.20
        version = 2
        proposals = aes128-sha256-modp2048

        local {
            auth = psk
            id = gateway-a.stateflux.lab
        }
        remote {
            auth = psk
            id = gateway-b.stateflux.lab
        }

        children {
            weak-tunnel {
                local_ts = 10.1.0.0/16
                remote_ts = 10.2.0.0/16
                esp_proposals = aes128-sha256
                rekey_time = 3600s
                start_action = start
            }
        }
    }
}

secrets {
    ike-lab02 {
        secret = "StatefluxControlledLabSecretKey2026!"
    }
}
