# STATEFLUX Controlled Lab — strongSwan base configuration
connections {
    net-net {
        local_addrs = 192.168.100.10
        remote_addrs = 192.168.100.20
        version = 2
        proposals = aes256gcm16-prfsha256-ecp384,aes128-sha256-modp2048

        local {
            auth = psk
            id = gateway-a.stateflux.lab
        }
        remote {
            auth = psk
            id = gateway-b.stateflux.lab
        }

        children {
            net-net {
                local_ts = 10.1.0.0/16
                remote_ts = 10.2.0.0/16
                esp_proposals = aes256gcm16-ecp384,aes128-sha256
                rekey_time = 3600s
                start_action = none
            }
        }
    }
}

secrets {
    ike-lab {
        secret = "StatefluxControlledLabSecretKey2026!"
    }
}
